### ISSUE TITLE
Неправильное название министерства

### ISSUE THREAD

**Issue by JleenDeniel** [swimmwatch/mai-latex-course-work-template#1]
В шаблоне на самой первой странице написано название министерства, которого больше не существует. Теперь оно называется Министерством науки и высшего образования
 https://minobrnauki.gov.ru/

**Comment by swimmwatch** [comment]
> В шаблоне на самой первой странице написано название министерства, которого больше не существует. Теперь оно называется Министерством науки и высшего образования
> https://minobrnauki.gov.ru/

Ок, исправлю. Спасибо

**Comment by swimmwatch** [comment]
В последнем коммите исправил.
